import crypto from "node:crypto";
import { env } from "@/env";
import type { UserSessionDto, UserRole } from "../types";

const AUTH_SECRET = env.AUTH_SECRET || "electa_local_jwt_secret_dev_32_bytes_long";
const LOCAL_ISSUER = "https://cognito-idp.ap-southeast-1.amazonaws.com/localstack_pool";

export interface CognitoTokenPayload {
  sub: string;
  email: string;
  name: string;
  picture?: string | undefined;
  avatarUrl?: string | undefined;
  "custom:organization"?: string | undefined;
  identities?:
    | Array<{
        userId: string;
        providerName: string;
        providerType: string;
        issuer: string | null;
        primary: boolean;
        dateCreated: number;
      }>
    | undefined;
  "cognito:groups"?: string[] | undefined;
  "custom:role"?: string | undefined;
  token_use: "id" | "access";
  iss: string;
  iat: number;
  exp: number;
}

function base64UrlEncode(str: string): string {
  return Buffer.from(str)
    .toString("base64")
    .replace(/=/g, "")
    .replace(/\+/g, "-")
    .replace(/\//g, "_");
}

function base64UrlDecode(str: string): string {
  let base64 = str.replace(/-/g, "+").replace(/_/g, "/");
  while (base64.length % 4) {
    base64 += "=";
  }
  return Buffer.from(base64, "base64").toString("utf8");
}

export function generateLocalCognitoToken(params: {
  userId: string;
  email: string;
  name: string;
  role?: UserRole | undefined;
  avatarUrl?: string | undefined;
  organizationName?: string | undefined;
  expiresInSeconds?: number | undefined;
}): string {
  const {
    userId,
    email,
    name,
    role = "USER",
    avatarUrl,
    organizationName,
    expiresInSeconds = 60 * 60 * 24 * 7, // 7 days
  } = params;

  const header = {
    alg: "HS256",
    typ: "JWT",
  };

  const now = Math.floor(Date.now() / 1000);
  const payload: CognitoTokenPayload = {
    sub: userId,
    email,
    name,
    picture: avatarUrl,
    avatarUrl,
    "custom:organization": organizationName,
    "cognito:groups": [role],
    "custom:role": role,
    token_use: "id",
    iss: LOCAL_ISSUER,
    iat: now,
    exp: now + expiresInSeconds,
  };

  const encodedHeader = base64UrlEncode(JSON.stringify(header));
  const encodedPayload = base64UrlEncode(JSON.stringify(payload));
  const signature = crypto
    .createHmac("sha256", AUTH_SECRET)
    .update(`${encodedHeader}.${encodedPayload}`)
    .digest("base64")
    .replace(/=/g, "")
    .replace(/\+/g, "-")
    .replace(/\//g, "_");

  return `${encodedHeader}.${encodedPayload}.${signature}`;
}

export function verifyLocalCognitoToken(token: string): UserSessionDto | null {
  if (!token || typeof token !== "string") {
    return null;
  }

  const parts = token.split(".");
  if (parts.length !== 3) {
    return null;
  }

  const [encodedHeader, encodedPayload, signature] = parts;
  if (!encodedHeader || !encodedPayload || !signature) {
    return null;
  }

  try {
    const header = JSON.parse(base64UrlDecode(encodedHeader)) as { alg?: string; typ?: string };
    const payload = JSON.parse(base64UrlDecode(encodedPayload)) as CognitoTokenPayload & {
      given_name?: string;
      family_name?: string;
      email_verified?: boolean;
    };
    const now = Math.floor(Date.now() / 1000);

    if (payload.exp && payload.exp < now) {
      return null; // Expired
    }

    // For local HS256 tokens generated by Electa, verify HMAC signature
    if (header.alg === "HS256") {
      const expectedSignature = crypto
        .createHmac("sha256", AUTH_SECRET)
        .update(`${encodedHeader}.${encodedPayload}`)
        .digest("base64")
        .replace(/=/g, "")
        .replace(/\+/g, "-")
        .replace(/\//g, "_");

      if (signature !== expectedSignature) {
        return null;
      }
    } else if (!payload.sub || !payload.email) {
      // For RS256 Cognito tokens, validate payload structure and required claims
      return null;
    }

    const role = (payload["custom:role"] ||
      payload["cognito:groups"]?.[0] ||
      "ORGANIZER") as UserRole;

    const name =
      payload.name ||
      (payload.given_name ? `${payload.given_name} ${payload.family_name || ""}`.trim() : "") ||
      payload.email.split("@")[0] ||
      "User";

    const avatarUrl = payload.avatarUrl || payload.picture || null;

    return {
      userId: payload.sub,
      email: payload.email,
      name,
      role,
      avatarUrl,
      organizationName: payload["custom:organization"] || null,
      expiresAt: new Date((payload.exp || now + 86400) * 1000).toISOString(),
    };
  } catch (err) {
    console.error("[Token Verification Error]", err);
    return null;
  }
}
